### ISSUE TITLE
Split drivers out into separate packages

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [andersfugmann/ppx_protocol_conv#1]
With jbuilder and maybe topkg it is pretty easy to split out subpackages (as the [Mirage project is documented](https://mirage.io/wiki/packaging). It would be nice if all the derivers which introduce dependencies (`xml-light`, `msgpck`, `yojson`) could be split into their own respective sub-derivers, so one can just depend on the parts that are required.

I'd look into it myself, but I thought I might as well create a tracking issue for this, so here it is.

**Comment by avsm** [comment]
That would be quite handy -- I was thinking of submitting Yaml, Ezjson serialisers since they share the same type -- that would clash with the yojson one though.

**Comment by andersfugmann** [comment]
Would you suggest creating a distinct package for each serializer? 
`ppx_protocol_conv` (base)
`ppx_protocol_conv-json`
`ppx_protocol_conv-xml-light`
`ppx_protocol_conv-msgpack`

**Comment by andersfugmann** [comment]
@avsm I don't see why an Yaml nor Ezjson would clash with the yojson driver? 
Can't yojson package coexist with the ezjson / yaml packages?
