### ISSUE TITLE
Doesn't seem to be working -- followed instructions in README to no avail

### ISSUE THREAD

**Issue by chetmurthy** [andersfugmann/ppx_protocol_conv#12]
I followed the README, but no de/serializer functions are getting generated.  I'm attaching a transcript.

(0) ocaml 4.07.1 installed via opam

(1) versions of (what I think are) relevant packages, freshly installed via opam

The following actions will be performed:
  - install yojson                  1.7.0
  - install ppx_derivers            1.0   [required by ppxlib]
  - install ocaml-migrate-parsetree 1.2.0 [required by ppxlib]
  - install ppxlib                  0.5.0 [required by ppx_protocol_conv]
  - install ppx_protocol_conv       3.1.3 [required by ppx_protocol_conv_json]
  - install ppx_protocol_conv_json  3.1.3

(2) transcript of toplevel interaction
#use "topfind";;
- : unit = ()
Findlib has been successfully loaded. Additional directives:
  #require "package";;      to load a package
  #list;;                   to list the available packages
  #camlp4o;;                to load camlp4 (standard syntax)
  #camlp4r;;                to load camlp4 (revised syntax)
  #predicates "p,q,...";;   to set these predicates
  Topfind.reset();;         to force that packages will be reloaded
  #thread;;                 to enable threads

- : unit = ()
# #require "ppx_protocol_conv_json";;
/home/chet/Hack/Ocaml/4.07.1/ocaml-base-compiler.4.07.1/lib/ppx_protocol_conv/runtime: added to search path
/home/chet/Hack/Ocaml/4.07.1/ocaml-base-compiler.4.07.1/lib/ppx_protocol_conv/runtime/protocol_conv.cma: loaded
/home/chet/Hack/Ocaml/4.07.1/ocaml-base-compiler.4.07.1/lib/ppx_protocol_conv/driver: added to search path
/home/chet/Hack/Ocaml/4.07.1/ocaml-base-compiler.4.07.1/lib/ppx_protocol_conv/driver/ppx_protocol_driver.cma: loaded
/home/chet/Hack/Ocaml/4.07.1/ocaml-base-compiler.4.07.1/lib/easy-format: added to search path
/home/chet/Hack/Ocaml/4.07.1/ocaml-base-compiler.4.07.1/lib/easy-format/easy_format.cma: loaded
/home/chet/Hack/Ocaml/4.07.1/ocaml-base-compiler.4.07.1/lib/biniou: added to search path
/home/chet/Hack/Ocaml/4.07.1/ocaml-base-compiler.4.07.1/lib/biniou/biniou.cma: loaded
/home/chet/Hack/Ocaml/4.07.1/ocaml-base-compiler.4.07.1/lib/yojson: added to search path
/home/chet/Hack/Ocaml/4.07.1/ocaml-base-compiler.4.07.1/lib/yojson/yojson.cma: loaded
/home/chet/Hack/Ocaml/4.07.1/ocaml-base-compiler.4.07.1/lib/ppx_protocol_conv_json: added to search path
/home/chet/Hack/Ocaml/4.07.1/ocaml-base-compiler.4.07.1/lib/ppx_protocol_conv_json/protocol_conv_json.cma: loaded
# open Protocol_conv
open Protocol_conv_json
;;

    #   type a = {
  x: int;
  y: string [@key "Y"]
} [@@deriving protocol ~driver:(module Json) ~flags:(`Mangle Json.mangle)]
;;

        type a = { x : int; y : string; }
#   
type b = A of int
       | B of int [@key "b"]
       | C
[@@deriving protocol ~driver:(module Json)] ;;

        type b = A of int | B of int | C
#

**Comment by andersfugmann** [comment]
It seems that the ppx_protocol_json (and possibly all the drivers) will not import ppx_protocol_conv. 
You need to explicitly `#require "ppx_protocol_conv"`.
I will fix this for future versions.

**Comment by andersfugmann** [comment]
New version released, which fixes the problem
