### ISSUE TITLE
Using a deriver causes base and ppxlib to be linked

### ISSUE THREAD

**Issue by copy** [andersfugmann/ppx_protocol_conv#19]
Consider this minimal example from the readme:

```
open Protocol_conv_json
type a = {
  x: int;
  y: string [@key "Y"];
  z: int list [@default [2;3]]
} [@@deriving protocol ~driver:(module Json)]
```

```
(executable
 (name test)
 (preprocess
  (pps ppx_protocol_conv_json))
 (libraries ppx_protocol_conv_json))
```

The resulting binary is 31 MB and contains both base (probably due to the inline tests) and ppxlib (including OCaml's compiler libs) to be linked. Checked by running `nm` on the executable, for example `nm _build/default/test.exe | grep camlBase`.

**Comment by andersfugmann** [comment]
Thanks for noticing. 

The base is expected, as it adds tail optimized tail recursive functions like List.map. 
However ppxlib should not be linked.

The change to have ppx_protocol_conv_json depend on ppx_protocol_conv was introduced in with #12, which causes ppslib to be lined. I will revert that. 

I will remove the dependency on ppxlib for all drivers.

**Comment by copy** [comment]
I believe this has been fixed in https://github.com/andersfugmann/ppx_protocol_conv/commit/3c2b1189943ab9cd2feec808bda948e877a02fea and https://github.com/andersfugmann/ppx_protocol_conv/commit/1be9d66f8f1ef60089d8c8f10b7135cc83fea40b.
