### ISSUE TITLE
Special case when type is called `t`

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [andersfugmann/ppx_protocol_conv#2]
I greatly enjoy the (common) case when a module is working on a specific type `t` then the derivers in ppx_deriving would not add `t_to_hest` and `t_of_hest` but rather `to_hest` and `of_hest`, avoiding some boilerplate.

It would be great if this module could at least create an alias of `of_hest` to `t_of_hest` and `to_hest` to `t_to_hest`, which would keep existing code running but add some convenience.

**Comment by Leonidas-from-XIV** [comment]
Oh I just realized that an alias is not enough, since it would also require modules to have a `t_of_hest` and `t_to_hest` implementation, whereas just naming them `of_hest` and `to_hest` would be better.

**Comment by andersfugmann** [comment]
I've implemented the alias so if the name of the type to generate conversions for is named `t`, an 
alias is created: `let of_hest = t_of_hest`. This makes recursion work if a module A references B.t_{from,to}_hest

Release 1.0.0 (available though opam) includes this change.
