### ISSUE TITLE
Support result type

### ISSUE THREAD

**Issue by darioteixeira** [andersfugmann/ppx_protocol_conv#20]
Type `result` has been part of Pervasives since 4.03.0.

**Comment by andersfugmann** [comment]
Rewriting to use mondic style result type throughout the code has two major deficiencies. 
1. No stacktraces. It will make it much harder to understand exactly at which point in the code deserialization failed. 
2. Monadic style parsing is way slower than using exceptions for error handling. 

Closing, as I don't think it will improve readability of the code, speed or debuggability.
