### ISSUE TITLE
Adapt to ppxlib 0.22.0

### ISSUE THREAD

**Issue by copy** [andersfugmann/ppx_protocol_conv#34]
It's currently constrained to `< "0.18.0"`:

```
% opam show ppx_protocol_conv |grep ppxlib
              "ppxlib" {>= "0.9.0" & < "0.18.0"}
```

**Comment by andersfugmann** [comment]
This limit was added as part of https://github.com/ocaml/opam-repository/pull/17360. I cannot access the logs referenced in the PR, so I do not know the rationale for this, other than rev-deps was complaining about this package. 

You are welcome to create a PR against the opam-repository. The code compiles just fine against ppxlib 0.22.0 (although the tests implicitly requires ppxlib 0.21.0)

**Comment by copy** [comment]
Thanks. I went ahead and proposed to adjust the constraints on opam-repository: https://github.com/ocaml/opam-repository/pull/18172
