### ISSUE TITLE
Support for Msgpck.Bytes

### ISSUE THREAD

**Issue by Thegaram** [andersfugmann/ppx_protocol_conv#4]
Hi, thanks for the great library!

I was wondering if you could add support for deserializing fields of type `Msgpck.Bytes` into OCaml fields (maybe of type `Bytes`?). I am communicating with a service whose response is correctly deserialized into `Msgpck.Bytes` (see [here](https://github.com/msgpack/msgpack/blob/master/spec.md#bin-format-family)) but the automatic conversion provided by `ppx_protocol_conv` is unable to handle this value.

**Comment by andersfugmann** [comment]
You can make your own conversion to convert to and from msgpack bytes:
```ocaml
module Bytes = struct
  type t = string
  let t_of_msgpack = Msgpck.to_bytes
  let t_to_msgpack = Msgpck.of_bytes
end
type test = { bytes: Bytes.t }
[@@deriving protocol ~driver:(module Msgpack)]

let () =
  let t = { bytes = "test" } in
  let m = test_to_msgpack t in
  let _t = test_of_msgpack m in
  ()
```
I will add this module to the msgpack conversion in the next version. Until then the above solution should work. Please let me know if it works for you.

(Overloading bytes is imho dangerous, as bytes are just mutable strings, but you can choose any ocaml type representation you like when defining you own serialization/deserialization functions.)
However, I'm puzzled that msgpack choose to implement both strings and bytes.

**Comment by Thegaram** [comment]
Thanks for the workaround @andersfugmann, It worked just fine!
