### ISSUE TITLE
Defining Map fields

### ISSUE THREAD

**Issue by Thegaram** [andersfugmann/ppx_protocol_conv#5]
I have an OCaml type defined like this:

```ocaml
type t = {
  messages : (string * string) list; [@key "Messages"]
} [@@deriving protocol ~driver:(module Msgpack)]
```

I would like to treat `messages` as `Msgpck.Map` but apparently `ppx_protocol_conv` treats it as `Msgpck.List`. When I try to unmarshal such a value, I get `list expected, {}`, which suggests that the underlying `Msgpck` structure is a `Map`, but this lib tries to read it as a `List`.

My question is: how to define fields as `Map`s instead of `List`?

**Comment by andersfugmann** [comment]
The type you defined is a list (the ocaml type). 
ocaml record types are converted to msgpack maps, so you will need to defined which fields to read from the map, i.e.

```ocaml 
type message = { field_a: string; field_b: string } 
and type t = {
  messages : message; [@key "Messages"]
} [@@deriving protocol ~driver:(module Msgpack)]
```
This will create a msgpack structure:
```
{
  Messages: {
    field_a: "some value a",
    field_b: "some value b"
  }
}
```

**Comment by andersfugmann** [comment]
As an alternative you can define your own serialization / deserialization for this type:
```ocaml
module Messages = struct
  type t = (string * string) list
  let t_of_msgpack m =
    Msgpck.to_map m
    |> List.map (fun (k, v) -> Msgpck.to_string k, Msgpck.to_string v)
  let t_to_msgpack l =
    List.map (fun (k, v) -> Msgpck.of_string k, Msgpck.of_string v) l
    |> Msgpck.of_map
end
type t = {
  messages: Messages.t; [@key "Messages"]
}
[@@deriving protocol ~driver:(module Msgpack)]
```

**Comment by Thegaram** [comment]
Thanks @andersfugmann! I work with dynamic fields, so the first solution you suggested does not work in my case but the second one is just right.
