### ISSUE TITLE
Failed to deserialize msgpck

### ISSUE THREAD

**Issue by vinczedani** [andersfugmann/ppx_protocol_conv#6]
Hi!

I am currently trying to deserialize a msgpacked message. I defined my object in the following way
```
type member = {
    name : string; [@key "Name"]
    ...
  } [@@deriving protocol ~driver:(module Msgpack)]

  type t = {
    members : member list; [@key "Members"]
  } [@@deriving protocol ~driver:(module Msgpack)]

  let to_msgpack = t_to_msgpack
  let from_msgpack = t_of_msgpack
```

When the data arrives I print it with
```
    print_endline (Msgpck.show members);
```
And it prints well, but after that I try to get the object back from Msgpck.t to Members.t with
```
    let deserialized = Members.from_msgpack members in
    print_endline "finished";
```
But it never prints anything. Is it possible that the deserialization process gets stuck somewhere?
I am new to ocaml, so it is possible that I messed up something.

Thanks in advance,
Daniel

**Comment by andersfugmann** [comment]
You need to remove the line `let to_msgpack = t_to_msgpack`, as
the ppx already defined to_msgpack for types named `t` and 
creates the opposite line (`let t_to_msgpack = to_msgpack`) for backward compatibility.
