### ISSUE TITLE
Feature request: [@default ...]

### ISSUE THREAD

**Issue by Niols** [andersfugmann/ppx_protocol_conv#9]
I come from `ppx_deriving_yojson`. When I switched to Ezjsonm, I discovered this project, and I must admit it find it really nice (in particular, the fact that there is support for other serialisation formats like Yaml). There is just one feature that I find really cool and that I miss here: the `[@default ...]` attribute. It allows to write:

```
type t =
    { bla : string [@default ""] ;
      blo: int list [@default [42]] ;
      blu: float }
[@@deriving protocol ~driver:(module ...)]
```

The fields `bla` and `blo` become optional in the input serialised value and, in case they're not there, the default is used. I don't know how easy it would be to add, or if you'd accept PR. I could give it a go.

**Comment by andersfugmann** [comment]
I will see when I get the time to implement this, but I would welcome if you would beat me to it with a PR.

**Comment by Niols** [comment]
Thanks!
